### PR TITLE
Add ATC

### PR DESCRIPTION
**Pull request by bjoernma**
See OpenRailwayMap/OpenRailwayMap#825 and OpenRailwayMap/OpenRailwayMap#824

### CODE REVIEW

**Review by Nakaner — APPROVED** [review]
Looks good to me (after test renderings).

If a track has PTC and ATC, PTC colour is rendered. Does this make sense? @JonathanBittner @davide84 

Example: https://www.openstreetmap.org/way/5703514 is rendered in PTC colour and has `railway:atc=yes` and `railway:ptc=yes`.

Map rendering of New York:

new-york-z11

Map rendering of Malmö, Sweden (and showing ETCS tracks in Denmark):

malmoe-z10

**Comment by davide84** [comment]
> If a track has PTC and ATC, PTC colour is rendered. Does this make sense? @JonathanBittner @davide84
From what I understand yes, PTC is more advanced than ATC.

On the other side, I must say that both "PTC" and "ATC" are very generical terms. The current tags seem to assume that ATC in North America is the same as in Scandinavia, while elsewhere I read that the Scandinavian system is basically the Portoguese one which has another name, and this confusion has delayed the introduction of the Portoguese system on the map.
My point is, this PR looks correct, but we need some discussion about tagging strategies and I would be more than happy to contribute. [This one](https://wiki.openstreetmap.org/wiki/Proposed_features/railway:train_protection) is for me the perfect starting point (sorry for linking that twice in two days but I really think that would unlock some issues!)

**Comment by DerDakon** [comment]
Deployed to the website. Rerendering will take a while.

**Comment by JonathanBittner** [comment]
PTC should dominate ATC, at least in North American usage.

**Pull request merged**
