### PR TITLE
ADD: Add ASFA support

### PR DESCRIPTION
**Pull request by armin762**
Same as https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/80 but for ASFA in Spain.

I tested the changes locally using kosmtk following the development guide.

Also I chosed a color(pink) that did not resemble any of the current ones(we're running out of colors :P)

### CODE REVIEW

**Comment by STemplar** [comment]
Hi @armin762 ,

You should change the signals.mapcss too. It changes the displayed Legend.
Regarding the colors, I have the same problem. I have added the following ATP systems:

Great Britain:
- tpws
- atp
- aws

Belgium
- tbl

Sweden, Norway, Portugal
- ebicab

Multiple countries/cities
- zub
- cbtc

How can we fix this? Adding diffferent linetypes? Group by continend and 'reuse' colors? Shall I open an issue about this?

**Comment by armin762** [comment]
Hi @Stemplar,

Thanks for the heads up, I added another pull request for the legend.

Yes, I agree the color issue should be discussed in another issue and there should be some rules about it. Whether consider using multiple colors in one line(although this could be later used to specify on lines where there's two systems) or different type lines like dotted, etc.

**Review by STemplar — APPROVED** [review]

**Comment by Nakaner** [comment]
@STemplar wrote:
> How can we fix this? Adding diffferent linetypes? Group by continend and 'reuse' colors? Shall I open an issue about this?

I am fine with reusing colours as long as the systems sharing a colour are not used on the same continent.

**Review by Nakaner — APPROVED** [review]
Madrid on zoom level 12:

madrid-z12

**Comment by STemplar** [comment]
> @STemplar wrote:
> 
> > How can we fix this? Adding diffferent linetypes? Group by continend and 'reuse' colors? Shall I open an issue about this?
> 
> I am fine with reusing colours as long as the systems sharing a colour are not used on the same continent.

Here is a proposal. I am all in for a discussion.:

afbeelding

**Pull request merged**
