### PR TITLE
ADD: rendering of Italian main signalling SCMT (railway:scmt)

### PR DESCRIPTION
**Pull request by davide84**
As per commit message. I think I changed all the pieces needed, I used previous changes and PR as documentation.

The color has been chosen avoid conflict with this other PR:
https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/77/files

### CODE REVIEW

**Review by Nakaner — APPROVED** [review]

**Comment by Nakaner** [comment]
Zoom level 7:

z7

Zoom level 9:

z9

**Comment by davide84** [comment]
Oh... thanks for the screenshots, it looks like my choice of colors hasn't been the best one. Is it too late to change it? Just the color.
I would rather go with #DD11FF and risk a conflict with the North America lines than generate confusion with ETCS.

Attached an image with the new color on the east coast, my original color on a small line on the north-east.
map

**Comment by DerDakon** [comment]
Sure, just go ahead and change the color.

**Comment by davide84** [comment]
Color changed and commit squashed. Will update the color in the repo with the legend as well. Thanks!

**Review by Nakaner — APPROVED** [review]

**Comment by Nakaner** [comment]
I deployed the change today and requested rerendering of the tiles covering Italy.

**Pull request merged**
