### PR TITLE
only allow explicitly whitelisted values for construction:railway

### LINKED ISSUE #72: Labels are rendered for monorails under construction
Similar to issue #43 monorails under construction have the labels appearing. The lines themselves, once properly tagged do not render.

Example: https://openrailwaymap.org/?style=standard&lat=33.43764603032683&lon=-112.01583981513977&zoom=16
Once I retagged the line under construction with construction:railway=monorail, my local renderer no longer shows the line, but does display the text labels.

### PR DESCRIPTION
**Pull request by DerDakon**
Hopefully fixes #72.

### CODE REVIEW

**Comment by JonathanBittner** [comment]
I haven't tested it but the code looks good.

**Comment by JonathanBittner** [comment]
on line 177 of standard_labels.mss you have an open curly brace '{' when you want a comma.

**Comment by DerDakon** [comment]
> on line 141 of standard_labels.mss you have an open curly brace '{' when you want a comma. Otherwise looks good

Thanks, fixed.

You can click right after the line number in the diff view so you can write such comments right in the code.

**Review by Nakaner — APPROVED** [review]
@DerDakon You missed a few locations where we filtered construction values as well. I found them and corrected it. Otherwise your patch would have worked half way only.

I pushed [my commit](https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/73/commits/d1d8e3a7702d6806575f842ef935258116b10fe1) to this branch. You can squash the commits if you want.

**Pull request merged**
