### PR TITLE
Add new symbols: Lf6/7, Lf4, Wn7, Zs2(v),El6 (through). Changed Sv0 symbol.

### PR DESCRIPTION
**Pull request by bjoernma**
New symbols esp. for 5km/h / 15km/h maxspeeds, see commit-comments

### CODE REVIEW

**Comment by DerDakon** [comment]
I wonder how much sense it makes to add these signal images without any users.

**Comment by bjoernma** [comment]
For Lf6/7 number 0.5 or 1.5, there are some mapped examples in germany
For El6, there is yet some tagging missing for double-left/double-right etc, and the "through" arrow definitely exists in the database 
For Lf4 number 1.5 and 0, there are as well mapped examples in the database (even if it's only one for "0", but it exists...) I'd expect some more to come with higher degree of mapping.
So I'd propose to approve at least those first ones. 
For Zs2(v) it's not as clear, so there I can go with you (as it's not clear, how they can be mapped at all..., see new issue)
For Wn7, it conflicts as well with the question how derailers can be mapped, so not as easy there as well, I see..

**Comment by DerDakon** [comment]
The point is that could try to add some rendering rules that actually use these images, then there would be no discussion ;)

**Comment by bjoernma** [comment]
Ahh, will add it, now it's clear :)

**Comment by Nakaner** [comment]
I reviewed the symbols but they need to be used by the map style in order to be useful.

**Comment by bjoernma** [comment]
Should now be included into mss files.

**Review by Nakaner — APPROVED** [review]
I fixed a regular expression.

Example renderings:

Adria near Dessau:

adria-z17

Bruchsal (no new signals to be shown, just to check existing ones):

bruchsal-z15

Duisburg Landschaftspark:

duisburg-landschaftspark-z17

Oppershofen:

oppershofen-z18

**Comment by DerDakon** [comment]
What's your preference? Squash some or all of these commits together or merge it as is?

**Comment by bjoernma** [comment]
Is now squashed and rebased. Thanks :)

**Pull request merged**
