### PR TITLE
Electrification style

### PR DESCRIPTION
**Pull request by Nakaner**
This is the current state of work on the electrification style.

Rastatt at zoom levels 11, 13 and 16:

electrification_rastatt_z11
electrification_rastatt_z13
electrification_rastatt_z16

Wendlingen (zoom level 11):

electrification_wendlingen_z11

Europe at zoom level 4 (The database used for this test contained data of Europe only):

electrification_z4

Sande (zoom level 8 and 12):

electrification_z8
electrification_z12

Karlsruhe (zoom level 17):
electrification_ka_z17

Power off section between Delitzsch u Bf and Rackwitz (bei Leipzig) at zoom level 17:
electrification_null_z17

### CODE REVIEW

**Comment by DerDakon** [comment]
The dashing you showed in the preview images is not in the style anymore, see also #14.

**Comment by jonsger** [comment]
So what is required for merge? Change the style of railway lines under construction?

**Comment by c933103** [comment]
Issues:
1. Currently, railway tagged as frequency=0 (explicitly DC electrification) and railway without specific frequency tag (could be just the editor forgot to put the tag in) apparently isn't being distinguished and both show a "=" sign after their voltage. If my observation is correct then please change the rendering to show DC electrification line differently from rail lines without frequency tag.
2. Currently, the style does not appears to indicate information like third rail electrification or overhead line? Can this be added into the style?
3. I don't understand way OSM way 244938138 and OSM way 41703938 are now rensered in different color despite they are both 1500V DC contact line electrification. Can someone explain what's their different?

**Comment by Nakaner** [comment]
@c933103 wrote:
> 1. Currently, railway tagged as frequency=0 (explicitly DC electrification) and railway without specific frequency tag (could be just the editor forgot to put the tag in) apparently isn't being distinguished and both show a "=" sign after their voltage. If my observation is correct then please change the rendering to show DC electrification line differently from rail lines without frequency tag.

I admit that I have never thought about ways with `voltage=*` but without `frequency=*`. I queried the database and got the following numbers of electrified ways with `railway=rail` and unset `frequency=*` tag. The following list is grouped by voltage (total number is 5964):

```
gis=# select count(1) as number, voltage from openrailwaymap_osm_line where osm_id > 0 and railway = 'rail' and electrified IS NOT NULL and electrified != 'no' and voltage IS NOT NULL AND frequency IS NULL group by voltage order by number desc;
 number | voltage 
--------+---------
   2151 | 3000
   1534 | 25000
   1412 | 1500
    451 | 800
    100 | 15000
     93 | 1200
     82 | 0
     58 | 600
     30 | 20000
     30 | 750
     14 | 50000
      3 | 33000
      2 | 3400
      2 | 10000
      1 | 138000
      1 | 1000
```

On the other hand, we have 753,912 ways with `frequency` set.

The MapCSS style does not show a `=` character if there is not frequency set. Therefore, I removed it a few minutes ago.

> 2. Currently, the style does not appears to indicate information like third rail electrification or overhead line? Can this be added into the style?

Yes, but this is out of scope for this pull request. The pull request aims to rebuild the MapCSS map style as that style is.

> 3. I don't understand way OSM way 244938138 and OSM way 41703938 are now rendered in different color despite they are both 1500V DC contact line electrification. Can someone explain what's their different?

There are not differences in rendering. Even their edit history does not explain any differences back then when you wrote your comment.

arrow

**Comment by DerDakon** [comment]
When you look on the other 1.5kV track at the upper right of your image, there are some segments that are rendered in gray. I suspect there are actually 2 tracks close to each other, one of them without electrification tagging.

**Comment by Nakaner** [comment]
> With the current tiles, I see the following problems:
> 
> * at zoom 7 and 8 existing lines with proposed/construction are just shown in grey (see Oldenburg - Wilhelmshaven)

I fixed this.

Zoom 8:

z8-small

Zoom 9:

z9-small


> * new tracks under construction with electrification are not shown at all (Bahnumfahrung Sande)

umfahrung-sande-small

The bug became visible because the track has neither `usage=*` nor `service=*`.

**Review by DerDakon — APPROVED** [review]
Let's start with what we have and improve incrementally, otherwise this will take another year or more.

**Pull request merged**
