### PR TITLE
Added rendering for PTC

### PR DESCRIPTION
**Pull request by JonathanBittner**
Added support for rendering North American Positive Train Control in the
signal style.

Partially addresses #37

### CODE REVIEW

**Comment by JonathanBittner** [comment]
Longer explanation: added code to render railway:ptc=yes as purple (tram color from standard/infrastructure) and assign it equal rank with ETCS.  I'm not tied to that color, feel free to suggest something different or suggest that the color/legend entry be shared with ETCS.

I took a look at the available tags [here](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Train_protection_systems): the relevant tags are railway:acses, railway:ases, railway:etms, and railway:itcs, and railway:ptc.  I did a tag usage survey and saw that railway:acses had 8 occurrences, and there were none for ases, etms, or itcs.  There are currently 803 ways using railway:ptc.  I added the railway:ptc tag to the 8 railway:asces nodes.  There are several other PTC systems being [approved](https://railroads.dot.gov/train-control/ptc/ptc-system-information) including CBTC and e-ATC.  

Most of the freight network has adopted I-ETMS (railway:etms).  ITCS was installed on one Amtrak line in Michigan.  ACSES II (railway:acses) is used by Amtrak on the Northeast Corridor, connected branches, and by several commuter authorities that also operate on Amtrak-owned lines.  ASES II is used on several New Jersey Transit lines.  One line in Maryland has both I-ETMS and ASCES II so the commuter operator could simply use I-ETMS on all of their lines.

It would be very complicated to add a color for each vendor's PTC implementation. Since most of these tags have never been used, it would be better to group everything under railway:ptc.  If desired, a text layer could be added later to show the specific PTC implementation.

**Comment by DerDakon** [comment]
Looks basically sane to me. Please rebase on current master.

**Review by Nakaner — APPROVED** [review]
Looks good to me.

ptc-z8

**Comment by DerDakon** [comment]
Please rebase to adapt to new changes in master. Tell us if you need any help.

**Comment by davide84** [comment]
Hi! I took the liberty to do the rebase, unfortunately I had to open a different PR from my repo but I retained the original author. See https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/86.
Hope this way of doing things is useful :)

**Comment by JonathanBittner** [comment]
Sorry, I don't have time to be active right now. Thanks to all who are pushing this through!

**Comment by Nakaner** [comment]
Replaced by #86.

**Pull request closed without merging**
