### PR TITLE
Ne13 and Ne12 rendering

### PR DESCRIPTION
**Pull request by besentv**
Very straightforward, example in Rauenstein (Thür):

image

### CODE REVIEW

**Review by Nakaner — APPROVED** [review]

**Comment by besentv** [comment]
Something I forgot, was that Ne13 can have a number assigned to it, which tells you about the amount of switches that will be passed. Though there isn't a tag for this yet (maybe just use ref) so I omitted it.

**Comment by Nakaner** [comment]
> Something I forgot, was that Ne13 can have a number assigned to it, which tells you about the amount of switches that will be passed. Though there isn't a tag for this yet (maybe just use ref) so I omitted it.

None of the railway lines I am used to has resetting switches. I doubt that I have ever seen any of these signals outside written signalling rules. :-) `railway:signal:resetting_switch:caption` would be the better tag. The `:caption` suffix is also in use for Ne 5 (Halttafel), Bü-Ankündetafel etc.

**Comment by besentv** [comment]
Could you maybe add this to the Wiki tagging page?

**Comment by Nakaner** [comment]
@besentv wrote:
> Could you maybe add this to the Wiki tagging page?

Done (both [German](https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_in_Germany) and [English](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging_in_Germany/B%C3%BC,_Ne,_Pf_and_So_Signals#Ne_13_Resetting_Point_Status_Signal) wiki page).

**Pull request merged**
